name: reellearning_fe
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.4.1
  firebase_app_check: ^0.3.2+1
  video_player: ^2.9.2
  intl: ^0.19.0
  simple_animations: ^5.0.2
  google_fonts: ^6.1.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/placeholder.png
    - assets/images/
    - assets/videos/
    - assets/videos/sample1.mp4
    - assets/videos/sample1.webm